language: bash

os:
- linux

env:
  - NODEVER=
  - NODEVER=10
  - NODEVER=8
  - NODEVER=6

services:
  - docker

script:
- |
  if [[ "$TRAVIS_OS_NAME" == 'linux' && -n "$NODEVER" ]]; then
    printf "FROM node:${NODEVER}-alpine\nWORKDIR /code\nADD package.json \/code\/package.json\nRUN apk add --update make\nENTRYPOINT []\nRUN npm install\nCMD [\"make\"]" > Dockerfile
    docker build --tag tester:${NODEVER}-alpine .
    docker run -it -v `pwd`:/code tester:${NODEVER}-alpine
  fi

notifications:
  email:
    on_success: never